socket.on('unauthorizedAttempt', async (attempt) => {
        log('unauthorizedAttempt', attempt);
})